; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-arduino-isr

[env:esp32-idf-rmt]
platform = espressif32
framework = espidf
board = esp32dev
build_flags =
  -DULTRASONIC_DRIVER_ESP_IDF_RMT


[env:esp32-arduino-isr]
platform = espressif32
board = esp32dev
framework = arduino
build_flags =
  -DULTRASONIC_DRIVER_ESP32_ARDUINO_ISR
build_src_filter =
  +<*>
  -<mock/*>
  -<drivers/*>
  +<drivers/esp32_arduino_isr/*>

[env:esp32-idf]
extends = env:esp32-idf-rmt

[env:esp32dev]
extends = env:esp32-arduino-isr
